### ISSUE TITLE
hi,i have a problem and need help~

### ISSUE THREAD

**Issue by zhuxinleibandou** [JimmyTai/react-native-color-picker-light#1]
Hello, it's great to meet a developer with such a good technology, this component is really great! But during use, it will appear: "RCTColorPickerView" was not found in the UIManager. How to solve it?

**Comment by zhuxinleibandou** [comment]
![IMG_8848](https://user-images.githubusercontent.com/18374383/85942040-5b1bd500-b959-11ea-93fa-ec86b4637a0e.PNG)

i dont have slove problem ，My technique is not good  >_<  thks

**Comment by JimmyTai** [comment]
Did you use ReactNative CLI or EXPO?

**Comment by zhuxinleibandou** [comment]
> Did you use ReactNative CLI or EXPO?

Thank you for your reply, not used CLI or EXPO, Need to use it？

**Comment by zhuxinleibandou** [comment]
I developed based on Mijia SDK （https://github.com/MiEcosystem/miot-plugin-sdk）, it should not be used CLI or EXPO

**Comment by JimmyTai** [comment]
It seems Mijia SDK not support native module.
