### ISSUE TITLE
Need some help( project with tuya SDK)

### ISSUE THREAD

**Issue by JanFrank** [JimmyTai/react-native-color-picker-light#18]
Hi,man , i need you help.
I use tuya SDK. GitHub url:https://github.com/tuya/tuya-panel-demo/tree/master/examples/basic
then, typed the `npm install react-native-color-picker-light`
install success.
then is do like this :
in /BASIC/src/containers/Home.js this file :
i change the code .such as :

`import ColorPicker from 'react-native-color-picker-light'
... some other codes ....
  render() {
    picker.current.setColor('#f0ce78');
    console.log(this,"thisVal");
    return (

      <View style={{ flex: 1 }}>
        <ColorPicker
  ref={picker}
  type="color"
  style={{ width: 200, height: 200 }}
  onColorChange={color  => {
	console.log('color:', color);
  }}
/>
           
        <ContentLayout  dpData={this.props.dpData} dispatch={this.props.dispatch} />
        <Footer  dpData={this.props.dpData}  dispatch={this.props.dispatch}  /> */}

      </View>
    );
  }
}

const picker = useRef();`

then i  use `npm install && npm run start `
When my phone open the app ,i fail.
error: bundling failed: UnableToResolveError: Unable to resolve module `react-native-color-picker-light` from `D:\tuya-panel-demo-master\basic\src\containers\Home.js`: Module does not exist in the module map or in these directories:
  D:\tuya-panel-demo-master\basic\node_modules

I only can make sure in    D:\tuya-panel-demo-master\basic\node_modules\react-native-color-picker-light this dir exist.
what can i do ? Or tuya SDK is no support?

**Comment by JimmyTai** [comment]
Sorry, I didn't have any experience on tuya SDK. I don't have any idea to resolve the issue you raised.

**Comment by JanFrank** [comment]
> 

OK,thx , i try to resold with another way.
